language: python
# command to install dependencies
# # command to run tests
install: true
script:
  - make test
after_success:
  - make coveralls
notifications:
    email:
        - opensource-tests@paylogic.com
